server:
  port: 10088
spring:
  profiles:
    active: dev
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        format: YAML
        enabled: true
        prefix: configuration
learn:
  api:
    user: http://learn-user
---
server:
  port: 10089
spring:
  profiles: beta