server:
  port: 10089
spring:
  profiles:
    active: dev
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        format: YAML
        enabled: true
        prefix: configuration
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

---
spring:
  profiles: beta