server:
  port: 10088
spring:
  profiles:
    active: dev
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${spring.profiles.active}}
        query-passing: true
      config:
        format: YAML
        enabled: true
        prefix: configuration
  thymeleaf:
    cache: false
logging:
  level:
    root: ERROR
learn:
  api:
    user: http://learn-user
---
server:
  port: 10089
spring:
  profiles: beta